--- #YAML:1.0
name:               Sys-Signals-Block
version:            0.03
abstract:           Simple interface to block delivery of signals
author:
    - Michael Schout <mschout@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:  0
    POSIX:            0
    Test::Exception:  0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
